services:
  mongodb:
    image: mongo:${MONGO_VERSION:-8.0.12}
    container_name: rocketchat-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    networks:
      - rocketchat
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  mongo-init-replica:
    image: mongo:${MONGO_VERSION:-8.0.12}
    container_name: rocketchat-mongo-init
    command: |
      bash -c '
      echo "Checking replica set status..."
      
      # First check if replica set is already initialized
      if mongosh mongodb:27017 --quiet --eval "rs.status().ok" | grep -q "1"; then
        echo "✅ Replica set already initialized and healthy"
        exit 0
      fi
      
      # Try to initialize replica set
      for i in $$(seq 1 10); do
        echo "Attempt $$i: Initializing replica set..."
        result=$$(mongosh mongodb:27017/rocketchat --quiet --eval \
          "try { rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"mongodb:27017\"}]}); print(\"SUCCESS\"); } catch(e) { if(e.message.includes(\"already initialized\")) { print(\"ALREADY_INIT\"); } else { print(\"ERROR: \\